### ISSUE TITLE
Fiber Implementation Docs

### ISSUE THREAD

**Issue by trapcodeio** [apitoolkit/apitoolkit-go#37]
Just came across this cool service on twitter and would love to know how i can integrate it in go fiber.

**Comment by tonyalaribe** [comment]
I'm working on this now, and we should have a Go fiber middleware soon

**Comment by tonyalaribe** [comment]
I'll close this now, since Fiber support landed in https://github.com/apitoolkit/apitoolkit-go/commit/a43af9d689dc180a0ac5ba6d9f8bde3512ca7697
